#!/usr/bin/env ruby

require_relative "../lib/synonym_searcher_jp.rb"

def pp lists, column = 4, w = 18
    column_count = 0
    lists.each { |e|
        print e
        print "　" * (w - e.size % w)
        column_count +=  (e.size / w + 1)
        if column_count >= column
            print "\n"
            column_count = 0
        end
    }
end

pp SynonymSearcherJp::fetch_wno_ruby(ARGV[0])

# require "thor"
#
# module SynonymSearcherJp
# 	class CLI < Thor
# 		default_command :fetch
# 		desc "fetch WORD",""
# 		def fetch word=""
# 			SynonymSearcherJp::fetch(word).each{|e| puts e}
# 		end
# 	end
# end
#
# SynonymSearcherJp::CLI.start
